language: java
jdk:
 - openjdk6
 - oraclejdk7
script: mvn clean install --batch-mode
matrix:
  allow_failures:
    - jdk: oraclejdk7
branches:
  only:
    - 1.11.x
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#OpenMRS"
    template:
      - "[%{repository}] [%{commit}] [%{author}] %{message} - %{build_url}"
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after
